// Generated by CoffeeScript 1.8.0
(function() {
  (function($) {
    var scrollElement, scrollSpeed, upperLimit;
    upperLimit = 500;
    scrollElement = $('#back-to-top');
    scrollSpeed = 500;
    scrollElement.hide();
    $(window).scroll(function() {
      var scrollTop;
      scrollTop = $(document).scrollTop();
      if (scrollTop > upperLimit) {
        return $(scrollElement).stop().fadeTo(300, 1);
      } else {
        return $(scrollElement).stop().fadeTo(300, 0);
      }
    });
    return $(scrollElement).click(function() {
      $('html, body').animate({
        scrollTop: 0
      }, scrollSpeed);
      return false;
    });
  })(jQuery);

}).call(this);
